/**
 * Machine-searchable error codes for runtime. Use at throw sites; central logger emits code in every error log.
 */
export const ERR_PROJECT_ROOT_REQUIRED = "ERR_PROJECT_ROOT_REQUIRED";
export const ERR_PROJECT_ROOT_NOT_DIR = "ERR_PROJECT_ROOT_NOT_DIR";
export const ERR_PROJECT_ROOT_INVALID = "ERR_PROJECT_ROOT_INVALID";
export const ERR_CONFIG_INVALID = "ERR_CONFIG_INVALID";
export const ERR_CONFIG_MISSING = "ERR_CONFIG_MISSING";
export const ERR_ACTIVATION_IN_PROGRESS = "ERR_ACTIVATION_IN_PROGRESS";
export const ERR_ENV_INVALID = "ERR_ENV_INVALID";
export const ERR_SCHEMA_VALIDATION = "ERR_SCHEMA_VALIDATION";
export const ERR_ROUTE_DRIFT = "ERR_ROUTE_DRIFT";
export const ERR_DEPS_NOT_SET = "ERR_DEPS_NOT_SET";
export const ERR_AGENT_FAILED = "ERR_AGENT_FAILED";
export const ERR_LLM_PROVIDER = "ERR_LLM_PROVIDER";
export const ERR_TRANSCRIPT_FETCHER = "ERR_TRANSCRIPT_FETCHER";
export const ERR_RULES_SNAPSHOT_EXTRACT = "ERR_RULES_SNAPSHOT_EXTRACT";
export const ERR_REPO_SCOPE_GENERATION = "ERR_REPO_SCOPE_GENERATION";
export const ERR_JSON_REPAIR = "ERR_JSON_REPAIR";
export const ERR_AGENT_CLI_CONTRACT = "ERR_AGENT_CLI_CONTRACT";
export const ERR_UNEXPECTED = "ERR_UNEXPECTED";
